version: '3.4'

services:
  cmdline:
    image: cmdline
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 cmdline/core.py "]
    ports:
      - 5678:5678
