name: Create a new Release

on:
  push:
    tags:
      - 'v*'

jobs:

  avoid_redundancy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  pyinstaller-win-build:
    runs-on: windows-latest
    steps:
      - name: Create Win Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'build.spec'
          requirements: 'requirements.txt'
          exe_path: ./dist/win
          upload_exe_with_name: 'scrapper-win'

  pyinstaller-linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Linux Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'build.spec'
          requirements: 'requirements.txt'
          exe_path: ./dist/linux
          upload_exe_with_name: 'scrapper-linux'

  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "scrapper.cfg", "./dist/linux/scrapper-linux.zip", "./dist/linux/scrapper-win.zip"
        bodyFile: "RELEASE.md"
