name: Create a new Release

on:
  push:
    tags:
      - 'v*'

jobs:

  pyinstaller-win-build:
    runs-on: windows-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Create Win Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'build.spec'
          requirements: 'requirements.txt'
          exe_path: ./dist/win
          upload_exe_with_name: 'scrapper-win'

  pyinstaller-linux-build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Create Linux Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'build.spec'
          requirements: 'requirements.txt'
          exe_path: ./dist/linux
          upload_exe_with_name: 'scrapper-linux'

  create-release:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    needs:
      - pyinstaller-win-build
      - pyinstaller-linux-build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "scrapper.cfg, ./dist/linux/scrapper-linux, ./dist/linux/scrapper-win"
        bodyFile: "RELEASE.md"
