name: Create a new Release

on:
  push:
    tags:
      - 'v*'

jobs:

  linter:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: weibullguy/python-lint-plus@v1.11.0
        with:
          python-root-list: "tests"
          virtual-env: "python-lint-plus"
          use-pylint: true
          pylint-version: 2.5.10


  pyinstaller-win-build:
    runs-on: windows-2022
    needs:
      - linter
    concurrency:
      group: pyinstaller-win-build-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Create Win Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'build.spec'
          requirements: 'requirements.txt'
          exe_path: ./dist/win
          upload_exe_with_name: 'binaries-win'

  pyinstaller-linux-build:
    runs-on: ubuntu-22.04
    needs:
      - linter
    concurrency:
      group: pyinstaller-linux-build-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Create Linux Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'build.spec'
          requirements: 'requirements.txt'
          exe_path: ./dist/linux
          upload_exe_with_name: 'binaries-linux'

  create-release:
    concurrency:
      group: create-release-${{ github.ref }}
      cancel-in-progress: true
    needs:
      - pyinstaller-win-build
      - pyinstaller-linux-build
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v3
      with:
        name: binaries-linux
        path: ./dist/linux
    - uses: actions/download-artifact@v3
      with:
        name: binaries-win
        path: ./dist/win

    - name: Zip win artifact for deployment
      run: zip win_release.zip ./dist/win/* -r -j
    - name: Zip linux artifact for deployment
      run: zip linux_release.zip ./dist/linux/* -r -j

    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "scrapper.cfg, win_release.zip, linux_release.zip"
        bodyFile: "RELEASE.md"
